// Isolated tools/smoke_video_workbench.py --serve fixture; real local encoding.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
function wav(seconds){const n=seconds*24000*2,b=Buffer.alloc(44+n);b.write('RIFF');b.writeUInt32LE(36+n,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(24000,24);b.writeUInt32LE(48000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n,40);return b;}
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:18197',out=process.argv[3]||'browser-results';await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1100}}),checks=[],errors=[];let page=await context.newPage();const attach=p=>{p.on('pageerror',e=>errors.push(String(e)));p.on('dialog',d=>d.accept());};attach(page);
 const waitText=(id,text)=>page.waitForFunction(([id,text])=>document.getElementById(id).textContent.includes(text),[id,text]);
 try{
  const fixture=await (await page.request.get(base+'/fixture')).json(),script=fixture.script,old=fixture.video,oldURL=base+'/videos/'+old.task.task_id;
  await page.goto(base+'/videos');await page.locator('.work-card').waitFor();assert.match(await page.locator('.work-card').innerText(),/研发进展/);await page.locator('.work-thumb img').waitFor();checks.push('completed_gallery_uses_titles_covers_dates');
  await page.locator('[data-star]').click();await page.waitForFunction(()=>document.querySelector('[data-star]').textContent==='★');await page.reload();await page.waitForFunction(()=>document.querySelector('[data-star]')?.textContent==='★');checks.push('favorite_survives_reload');
  await page.goto(oldURL);await page.waitForFunction(()=>document.getElementById('player').readyState>=1);assert.ok(await page.locator('#player').evaluate(v=>v.duration)>1);await page.locator('#player').evaluate(v=>{v.muted=true;return v.play();});await page.waitForFunction(()=>document.getElementById('player').currentTime>.1);await page.locator('#player').evaluate(v=>v.pause());checks.push('real_h264_preview_plays_in_browser');
  await page.locator('#work-name').fill('每日精选·离线示例');await page.locator('#work-notes').fill('用于检验作品库检索与导出');await page.locator('#save-work').click();await waitText('work-message','已保存');await page.reload();assert.equal(await page.locator('#work-name').inputValue(),'每日精选·离线示例');const detail=await (await page.request.get(base+'/api/video/tasks/'+old.task.task_id)).json();assert.equal(detail.title,script.document.title);checks.push('work_metadata_preserved_without_rewriting_video_title');
  await page.goto(base+'/videos');await page.locator('#work-query').fill('检索与导出');await page.getByRole('button',{name:'筛选作品',exact:true}).click();await waitText('work-count','共 1 条');assert.match(await page.locator('.work-card').innerText(),/每日精选/);checks.push('search_matches_saved_notes');
  await page.goto(oldURL);await page.locator('#archived').check();await page.locator('#save-work').click();await waitText('work-message','已保存');await page.goto(base+'/videos');await waitText('work-count','共 0 条');await page.locator('#work-archived').check();await page.getByRole('button',{name:'筛选作品',exact:true}).click();await waitText('work-count','共 1 条');await page.goto(oldURL);await page.locator('#archived').uncheck();await page.locator('#save-work').click();await waitText('work-message','已保存');checks.push('archive_and_restore_without_deleting_artifacts');
  await page.locator('#remake').click();await page.waitForURL('**/video?from_task=*');assert.match(await page.locator('main').innerText(),/本次使用当前脚本/);await waitText('capabilities','编码环境可用');await page.locator('#diagnostic-details summary').click();assert.match(await page.locator('#diagnostics').innerText(),/H.264 \/ AAC/);checks.push('reuse_configuration_and_actionable_environment_checks');
  const previews=[];for(const template of ['brief','explain','timeline']){await page.locator('.template-choice-input[value='+template+']').check();await page.locator('#preview').click();await waitText('message','画面预览已更新');await page.waitForFunction(()=>!document.getElementById('preview').disabled);previews.push(await page.locator('#preview-image').getAttribute('src'));}assert.equal(new Set(previews).size,3);checks.push('three_real_template_previews');
  await page.locator('#kind').selectOption('image');await page.locator('#file').setInputFiles({name:'演示画面.png',mimeType:'image/png',buffer:await fs.readFile('docs/validation-0.10.0/demo/brief-preview.png')});await page.locator('#upload').click();await waitText('message','素材上传完成');await page.locator('.image-choice').uncheck();const imageId=await page.locator('.image-choice').getAttribute('value');await page.locator('.scene-image').last().selectOption(imageId);checks.push('per_segment_image_assignment');
  await page.locator('#kind').selectOption('audio');await page.locator('#file').setInputFiles({name:'浏览器测试配音.wav',mimeType:'audio/wav',buffer:wav(2)});await page.locator('#upload').click();await page.waitForFunction(()=>document.getElementById('audio-id').options.length>1);await page.locator('#backend').selectOption('uploaded');
  const text=script.document.segments.map(s=>(s.kind==='analysis'?'分析：':'')+s.text);
  await page.locator('#srt').fill('1\n00:00:00,000 --> 00:00:02,000\n'+text.join(''));await page.locator('#preflight').click();await waitText('preflight-result','跨越脚本段落');assert.equal(await page.locator('#submit-video').isDisabled(),true);checks.push('cross_segment_srt_is_rejected_before_queueing');
  const srt='1\n00:00:00,000 --> 00:00:01,000\n'+text[0]+'\n\n2\n00:00:01,000 --> 00:00:02,000\n'+text[1];await page.locator('#srt-file').setInputFiles({name:'测试字幕.srt',mimeType:'text/plain',buffer:Buffer.from(srt)});await page.waitForFunction(text=>document.getElementById('srt').value===text,srt);await page.locator('#preflight').click();await waitText('preflight-result','检查通过');assert.equal(await page.locator('#submit-video').isEnabled(),true);await page.locator('.template-choice-input[value=explain]').check();assert.equal(await page.locator('#submit-video').isDisabled(),true);await page.locator('#preflight').click();await waitText('preflight-result','检查通过');checks.push('srt_file_import_and_preflight_invalidates_on_changes');
  await page.locator('#preview-scene').selectOption('1');await page.locator('#preview').click();await waitText('preview-hint','第 2 段');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'video-setup.png'),fullPage:true});
  await page.locator('#submit-video').click();await page.waitForURL(url=>url.pathname.startsWith('/videos/')&&url.pathname!==new URL(oldURL).pathname);const taskURL=page.url(),taskId=new URL(taskURL).pathname.split('/').at(-1);await page.close();page=await context.newPage();attach(page);await page.goto(taskURL);await waitText('status','失败');await waitText('recovery-message','完整配音检查点有效');assert.match(await page.locator('#error').innerText(),/模拟编码中断/);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'video-recovery.png'),fullPage:true});checks.push('closed_page_retains_failure_and_audio_recovery_advice');
  await page.locator('#retry').click();await waitText('status','已完成');await page.locator('#player').waitFor({state:'visible'});await page.waitForFunction(()=>document.getElementById('player').readyState>=1);assert.match(await page.locator('#status').innerText(),/尝试 2 次/);checks.push('retry_reuses_audio_and_completes_real_render');
  const result=await (await page.request.get(base+'/api/video/tasks/'+taskId)).json();assert.equal(result.scenes[0].image_id,null);assert.equal(result.scenes[1].image_id,imageId);const timing=await (await page.request.get(base+'/api/video/tasks/'+taskId+'/files/scene_timeline.json')).json();assert.equal(timing.frames.at(-1).end,2);assert.equal(timing.scenes[1].kind,'analysis');checks.push('exported_scene_timing_keeps_image_and_analysis_links');
  const partial=await page.request.get(base+'/api/video/tasks/'+taskId+'/files/video.mp4',{headers:{Range:'bytes=0-99'}});assert.equal(partial.status(),206);const zip=await page.request.get(base+'/api/video/tasks/'+taskId+'/files/video_bundle.zip?download=true');assert.equal(zip.status(),200);assert.match(zip.headers()['content-disposition'],/attachment/);assert.ok(await page.getByRole('link',{name:'字幕 SRT',exact:true}).isVisible());await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'video-result.png'),fullPage:true});checks.push('mp4_range_and_video_subtitle_bundle_downloads');
  await page.goto(base+'/videos?status=all');await waitText('work-count','共 2 条');await page.locator('#work-template').selectOption('explain');await page.getByRole('button',{name:'筛选作品',exact:true}).click();await waitText('work-count','共 1 条');const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(result.task.created_at));await page.locator('#work-from').fill(day);await page.locator('#work-to').fill(day);await page.getByRole('button',{name:'筛选作品',exact:true}).click();await waitText('work-count','共 1 条');await page.locator('#reset-works').click();await waitText('work-count','共 2 条');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'video-library.png'),fullPage:true});checks.push('gallery_template_date_filters_and_preserved_previous_work');
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'video-library-mobile.png'),fullPage:true});await page.goto(base+'/scripts/'+script.package_key+'/video');await waitText('capabilities','编码环境可用');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.goto(taskURL);await waitText('status','已完成');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('library_setup_and_result_fit_mobile');
  assert.deepEqual(errors,[]);checks.push('no_javascript_errors');const report={passed:checks.length,checks,browser:browser.version(),errors};await fs.writeFile(path.join(out,'video-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
