// Run with the isolated tools/smoke_events.py fixture server.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:18195',out=process.argv[3]||'browser-results';await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN||undefined,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),checks=[],errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('dialog',d=>d.accept());
 const status=text=>page.waitForFunction(text=>document.getElementById('work-message').textContent.includes(text),text);
 try{
  await page.goto(base+'/events');await page.getByText('新建事件专题',{exact:true}).click();await page.locator('#new-event-title').fill('芯片研发进展（离线演示）');await page.getByRole('button',{name:'创建专题',exact:true}).click();await page.waitForURL('**/events/evt_*');const eventURL=new URL(page.url()).origin+new URL(page.url()).pathname,key=new URL(eventURL).pathname.split('/').at(-1);
  await page.getByRole('heading',{name:'芯片研发进展（离线演示）'}).waitFor();checks.push('create_named_event');
  await page.locator('[data-tab=sources]').click();await page.locator('#library-query').fill('芯片');await page.getByRole('button',{name:'搜索新闻库',exact:true}).click();
  await page.locator('[data-add-source=fixture_a]').click();await page.locator('[data-remove-source=fixture_a]').waitFor();await page.locator('[data-add-source=fixture_b]').click();await page.locator('[data-remove-source=fixture_b]').waitFor();checks.push('add_existing_library_reports');
  await page.locator('[data-tab=moments]').click();await page.locator('#new-moment').click();await page.locator('#moment-title').fill('研发计划公布');await page.locator('#moment-description').fill('示例团队公布研发计划，作为本专题的起点。');await page.locator('#moment-time-kind').selectOption('occurred');await page.locator('#moment-start').fill('2026-09-01');await page.locator('.evidence-check[value=fixture_a]').check();await page.locator('#moment-reviewed').check();await page.locator('#save-moment').click();await page.locator('#moment-dialog').waitFor({state:'hidden'});
  assert.match(await page.locator('#moments-list').innerText(),/发生日期 · 2026-09-01/);assert.match(await page.locator('#moments-list').innerText(),/2026-09-02/);checks.push('occurrence_vs_publication_and_pinned_quote');
  await page.locator('#new-moment').click();await page.locator('#moment-title').fill('后续实验时间待确认');await page.locator('#moment-description').fill('报道提到后续实验，具体日期尚不明确。');await page.locator('.evidence-check[value=fixture_b]').check();await page.locator('#save-moment').click();await page.locator('#moment-dialog').waitFor({state:'hidden'});assert.match(await page.locator('#moments-list').innerText(),/时间未知/);checks.push('unknown_time_node');
  await page.reload();assert.equal(await page.locator('.moment').count(),2);await page.screenshot({path:path.join(out,'event-timeline.png'),fullPage:true});checks.push('nodes_survive_reload');
  const exported=await (await page.request.get(base+'/api/events/'+key+'/evidence-export')).json();assert.equal(exported.moments.length,2);assert.equal(exported.source_versions.length,2);assert.ok(exported.source_versions[0].document.content);checks.push('export_contains_immutable_source_documents');
  await page.locator('[data-tab=sources]').click();await page.locator('[data-remove-source=fixture_a]').click();await status('引用');checks.push('referenced_report_removal_guard');
  await page.locator('[data-tab=research]').click();await page.locator('#research-query').fill('芯片研发背景');await page.locator('#run-research').click();await page.locator('.research-pick').waitFor();
  let articles=await (await page.request.get(base+'/api/articles?paginated=true')).json();assert.equal(articles.total,2);checks.push('external_search_stays_candidate_until_selected');
  await page.locator('.research-pick').check();await page.locator('#import-research').click();await page.waitForFunction(()=>document.getElementById('research-message').textContent.includes('已收录'));
  articles=await (await page.request.get(base+'/api/articles?paginated=true')).json();assert.equal(articles.total,3);await page.screenshot({path:path.join(out,'event-research.png'),fullPage:true});checks.push('selected_research_import_and_provenance');
  await page.locator('[data-tab=relations]').click();await page.locator('#event-query').fill('计划');await page.getByRole('button',{name:'搜索事件',exact:true}).click();await page.locator('[data-target=fixture_background]').click();await page.waitForFunction(()=>!document.getElementById('target-label').textContent.includes('尚未选择'));await page.locator('#relation-kind').selectOption('background');await page.locator('#relation-note').fill('参考此前计划的背景材料');await page.locator('#add-relation').click();await page.locator('#relations-list [data-unrelate]').waitFor();checks.push('link_background_event');
  await page.locator('[data-tab=sources]').click();await page.locator('.split-pick[value=fixture_b]').check();await page.locator('[data-tab=relations]').click();await page.locator('#split-title').fill('后续实验跟踪专题');await page.locator('#split-note').fill('将后续实验单独跟踪');await page.locator('#split-event').click();await page.waitForURL(url=>url.pathname.startsWith('/events/evt_')&&url.pathname!==new URL(eventURL).pathname);
  const splitURL=page.url();await page.getByRole('heading',{name:'后续实验跟踪专题'}).waitFor();assert.equal(await page.locator('.moment').count(),1);assert.match(await page.locator('.moment').innerText(),/后续实验时间待确认/);checks.push('split_moves_wholly_supported_nodes');
  await page.locator('[data-tab=relations]').click();await page.locator('#event-query').fill('芯片研发进展');await page.getByRole('button',{name:'搜索事件',exact:true}).click();await page.locator('[data-target="'+key+'"]').click();await page.waitForFunction(()=>document.getElementById('target-label').textContent.includes('芯片研发进展'));await page.locator('#relation-note').fill('演示完成后合并归档');await page.locator('#merge-event').click();await page.waitForURL(url=>url.pathname===new URL(eventURL).pathname);assert.equal(await page.locator('.moment').count(),2);checks.push('merge_preserves_nodes_and_sources');
  await page.goto(splitURL);await page.locator('#merged-notice').waitFor({state:'visible'});assert.match(await page.locator('#merged-notice').innerText(),/合并后的专题/);checks.push('archived_event_retains_original_url');
  await page.goto(eventURL+'#activity');assert.match(await page.locator('#activity-list').innerText(),/接收合并/);await page.screenshot({path:path.join(out,'event-history.png'),fullPage:true});checks.push('curation_history_visible');
  await page.goto(eventURL);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'event-mobile.png'),fullPage:true});checks.push('mobile_no_horizontal_overflow');
  await page.setViewportSize({width:1440,height:1050});await page.goto(base+'/profiles');await page.locator('#name').fill('关键词检索演示');await page.locator('#collection-mode').selectOption('search');await page.locator('#search-query').fill('芯片研发计划');await page.locator('#save-profile').click();await page.waitForFunction(()=>document.getElementById('profile-message').textContent.includes('已保存'));
  await page.locator('#copy-profile').click();assert.equal(await page.locator('#collection-mode').inputValue(),'search');assert.equal(await page.locator('#search-query').inputValue(),'芯片研发计划');await page.locator('#name').fill('关键词检索副本');await page.locator('#save-profile').click();await page.waitForFunction(()=>document.getElementById('profile-message').textContent.includes('已保存'));await page.goto(base+'/profiles?selected='+encodeURIComponent('关键词检索副本'));assert.equal(await page.locator('#collection-mode').inputValue(),'search');assert.equal(await page.locator('#search-query').inputValue(),'芯片研发计划');checks.push('keyword_strategy_save_copy_reload');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,'keyword-strategy.png'),fullPage:true});
  assert.deepEqual(errors,[]);checks.push('no_javascript_errors');const result={passed:checks.length,checks,browser:browser.version(),errors};await fs.writeFile(path.join(out,'event-browser-report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
