// Requires tools/smoke_scripts.py; no real model or news calls.
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:18196',out=process.argv[3]||'browser-results';await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN||undefined,args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1100}}),checks=[],errors=[];
 const attach=page=>{page.on('pageerror',e=>errors.push(String(e)));page.on('dialog',d=>d.accept());};let page=await context.newPage();attach(page);
 const waitMessage=text=>page.waitForFunction(text=>document.getElementById('message').textContent.includes(text),text);
 try{
  await page.goto(base+'/events/fixture_topic');await page.getByRole('link',{name:'根据已核对脉络生成脚本 →'}).click();await page.getByRole('heading',{name:'生成有据脚本'}).waitFor();
  assert.equal(await page.locator('.moment-choice:disabled').count(),1);await page.locator('#submit-generation').click();assert.match(await page.locator('#generation-error').innerText(),/至少选择/);checks.push('requires_reviewed_node_selection');
  for(const input of await page.locator('.moment-choice:enabled').all())await input.check();await page.locator('#generation-mode').selectOption('recap');await page.locator('#generation-style').selectOption('plain');await page.locator('#generation-duration').selectOption('90');await page.locator('#generation-backend').selectOption('llm');await page.screenshot({path:path.join(out,'script-generation.png'),fullPage:true});checks.push('mode_duration_style_and_backend_choices');
  await page.locator('#submit-generation').click();await page.waitForURL('**/tasks/*');const taskURL=page.url(),tid=new URL(taskURL).pathname.split('/').at(-1);await page.close();page=await context.newPage();attach(page);await page.goto(taskURL);await page.locator('#script-result').waitFor({state:'visible'});assert.match(await page.locator('#status').innerText(),/已完成/);checks.push('background_result_survives_closed_page');
  await page.locator('#script-result').click();await page.waitForURL('**/scripts/pkg_*');const scriptURL=page.url(),key=new URL(scriptURL).pathname.split('/').at(-1);await page.locator('.segment-card').first().waitFor();assert.equal(await page.locator('.segment-card').count(),2);assert.equal(await page.locator('#script-text').evaluate(e=>e.readOnly),true);assert.equal(await page.locator('#duration').inputValue(),'90');checks.push('structured_segments_and_generated_narration');
  assert.match(await page.locator('aside').innerText(),/E1 · 来源 r1/);assert.match(await page.locator('aside').innerText(),/E2 · 来源 r1/);checks.push('visible_pinned_versions_and_node_snapshot');
  await page.locator('.part-kind').last().selectOption('analysis');await page.locator('.part-text').last().fill('仅凭目前材料，还不能判断后续实验何时完成。');await page.locator('.part-visual').last().fill('阶段结果卡与后续日期待确认提示');await page.locator('.part-assets').last().fill('准备阶段结果原文截图，核对素材授权');assert.match(await page.locator('#script-text').inputValue(),/分析：仅凭/);await page.locator('#save').click();await waitMessage('已保存');assert.match(await page.locator('#revision').innerText(),/r2/);checks.push('edit_analysis_storyboard_and_asset_needs');
  await page.locator('.segment-card').first().locator('summary').click();await page.locator('.segment-card').first().locator('.part-evidence:checked').uncheck();await page.locator('#save').click();await waitMessage('本地输入已保留');assert.equal(await page.locator('.segment-card').first().locator('.part-evidence:checked').count(),0);await page.locator('#reload').click();await waitMessage('已加载');checks.push('invalid_citation_rejected_without_losing_local_input');
  await page.locator('.part-up').last().click();await page.locator('#save').click();await waitMessage('已保存');assert.equal(await page.locator('.part-kind').first().inputValue(),'analysis');await page.reload();await page.locator('#revision').getByText('r3',{exact:true}).waitFor();assert.equal(await page.locator('.part-kind').first().inputValue(),'analysis');checks.push('reorder_and_reload_retains_segment_identity');
  await page.locator('#add-segment').click();assert.equal(await page.locator('.segment-card').count(),3);await page.locator('.part-text').last().fill('供编辑补充的事实段。');await page.locator('.part-remove').last().click();assert.equal(await page.locator('.segment-card').count(),2);await page.locator('#reload').click();await waitMessage('已加载');checks.push('add_remove_segment_controls');
  await page.selectOption('#history','2');await page.locator('#restore').click();await waitMessage('已恢复');assert.equal(await page.locator('.part-kind').last().inputValue(),'analysis');assert.match(await page.locator('#revision').innerText(),/r4/);checks.push('restore_keeps_facts_analysis_and_storyboard');
  await page.screenshot({path:path.join(out,'script-editor.png'),fullPage:true});await page.locator('#submit-review').click();await waitMessage('审核状态已更新');await page.locator('#sources-checked').check();await page.locator('#wording-checked').check();await page.locator('#approve').click();await page.waitForFunction(()=>document.getElementById('status').textContent==='已通过');await page.locator('#export').click();await page.locator('#download').waitFor({state:'visible'});const download=await page.request.get(new URL(await page.locator('#download').getAttribute('href'),base).href);assert.equal(download.status(),200);await fs.writeFile(path.join(out,'approved-evidence-example.zip'),await download.body());checks.push('review_and_download_evidence_production_bundle');
  const script=await (await page.request.get(base+'/api/scripts/'+key)).json();assert.equal(script.document.segments[1].assets,'准备阶段结果原文截图，核对素材授权');assert.ok(script.document.script_text.includes('分析：'));checks.push('saved_api_matches_editor_and_plain_text_contract');
  await page.getByRole('link',{name:'制作视频',exact:true}).click();await page.getByRole('heading',{name:'制作视频',exact:true}).waitFor();checks.push('approved_script_continues_to_video_setup');
  await page.goto(scriptURL);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(out,'script-editor-mobile.png'),fullPage:true});await page.goto(base+'/events/fixture_topic/generate');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('generation_and_editor_fit_mobile');await page.setViewportSize({width:1440,height:1100});
  await page.locator('.moment-choice:enabled').first().check();await page.locator('#generation-mode').selectOption('explain');await page.locator('#generation-backend').selectOption('llm');await page.locator('#submit-generation').click();await page.waitForURL('**/tasks/*');await page.waitForFunction(()=>document.getElementById('status').textContent==='失败');assert.match(await page.locator('#error').innerText(),/模拟模型首次失败/);assert.equal(await page.locator('#script-result').isVisible(),false);await page.locator('#retry').click();await page.locator('#script-result').waitFor({state:'visible'});assert.equal(await page.locator('#attempts').innerText(),'2');checks.push('visible_failure_retry_and_result_recovery');
  await page.goto(base+'/scripts?event_key=fixture_topic');assert.equal(await page.getByRole('link',{name:'打开草稿',exact:true}).count(),2);await page.screenshot({path:path.join(out,'script-workbench.png'),fullPage:true});checks.push('workbench_lists_tasks_and_separate_drafts');
  await page.goto(base+'/events/fixture_topic/generate');await page.locator('.moment-choice:enabled').first().check();await page.locator('#generation-backend').selectOption('llm');await page.locator('#submit-generation').click();await page.waitForURL('**/tasks/*');await page.locator('#cancel').click();await page.waitForFunction(()=>document.getElementById('status').textContent==='已取消');assert.equal(await page.locator('#script-result').isVisible(),false);checks.push('cancel_does_not_create_late_draft');
  assert.deepEqual(errors,[]);checks.push('no_javascript_errors');const result={passed:checks.length,checks,browser:browser.version(),errors};await fs.writeFile(path.join(out,'scripts-browser-report.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
