const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const base=process.argv[2]||'http://127.0.0.1:18199',out=process.argv[3]||'task-monitor-browser-results';await fs.mkdir(out,{recursive:true});
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN||undefined,args:['--no-sandbox']});const ctx=await browser.newContext({viewport:{width:1440,height:1000}});
 const errors=[],checks=[];ctx.on('page',p=>p.on('pageerror',e=>errors.push(String(e))));const page=await ctx.newPage();
 const api=async(url,data)=>{const r=await(data===undefined?ctx.request.get(base+url):ctx.request.post(base+url,{data}));assert.ok(r.ok(),await r.text());return r.json();};
 async function ready(){await page.waitForFunction(()=>document.querySelector('#queue-notice').textContent.startsWith('状态更新于'));}
 async function until(fn){for(let i=0;i<150;i++){if(await fn())return;await new Promise(r=>setTimeout(r,100));}throw new Error('timeout');}
 const shot=async name=>{await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});};
 try{
  const f=await api('/fixture');await page.goto(base+'/tasks');await ready();assert.equal(await page.locator('#count-total').textContent(),'117');assert.equal(await page.locator('#count-queued').textContent(),'3');assert.match(await page.locator('#worker-state').textContent(),/未运行/);checks.push('global_counts_and_stopped_local_worker_are_visible');
  await page.locator('a[href="/tasks?status=queued"]').click();await ready();const rows=page.locator('#task-list tr');assert.equal(await rows.count(),3);assert.match(await rows.nth(2).textContent(),/队列第 3 位/);checks.push('queue_order_matches_claim_order');
  await page.locator('[name=kind]').selectOption('daily_script');await page.getByRole('button',{name:'筛选任务',exact:true}).click();await until(async()=>await page.locator('#task-list tr').count()===1);assert.match(await rows.first().textContent(),/队列第 2 位/);assert.equal(await page.locator('#count-queued').textContent(),'3');checks.push('filtered_list_keeps_global_queue_position');await shot('queue-filtered');
  await page.reload();await ready();assert.equal(await page.locator('[name=kind]').inputValue(),'daily_script');checks.push('filter_url_survives_reload');
  await page.locator('#clear-filters').click();await ready();await page.locator('[name=query]').fill('历史记录');await page.getByRole('button',{name:'筛选任务',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#queue-total').textContent.includes('112 项'));assert.equal(await rows.count(),25);
  for(let i=0;i<4;i++){await page.locator('#next').click();await page.waitForFunction(n=>document.querySelector('#paging').textContent.includes('第 '+n+' 页'),i+2);}assert.equal(await rows.count(),12);assert.equal(await page.locator('#next').isDisabled(),true);checks.push('history_beyond_one_hundred_is_paginated');
  await page.goBack();await page.waitForFunction(()=>document.querySelector('#paging').textContent.includes('第 4 页'));checks.push('browser_back_restores_filtered_page');
  await page.locator('#clear-filters').click();await ready();await page.locator('[name=query]').fill('%_');await page.locator('[name=date_from]').fill('2026-09-30');await page.locator('[name=date_to]').fill('2026-09-30');await page.getByRole('button',{name:'筛选任务',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#queue-total').textContent.includes('1 项'));assert.match(await rows.first().textContent(),/日期边界/);checks.push('literal_search_and_shanghai_date_boundary');
  await page.locator('[name=timezone]').fill('UTC');await page.getByRole('button',{name:'筛选任务',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#queue-total').textContent.includes('0 项'));checks.push('timezone_changes_date_results');
  await page.locator('a[href="/tasks?status=failed"]').click();await ready();assert.match(await rows.first().textContent(),/模拟上游不可用/);await rows.first().getByRole('link',{name:'查看失败与处理',exact:true}).click();await page.waitForURL('**/tasks/failure');assert.equal(await page.locator('#retry').isDisabled(),false);assert.match(await page.locator('#queue-duration').textContent(),/提交至结束/);checks.push('failure_filter_leads_to_existing_retry_and_diagnostics');
  await page.goto(base+'/tasks/'+f.trial);await page.waitForFunction(()=>document.querySelector('#queue-position').textContent.includes('第 3 位'));await page.locator('#cancel').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='已取消');await page.waitForFunction(()=>document.querySelector('#queue-position').textContent==='本任务已结束。');await page.locator('#retry').click();await page.waitForFunction(()=>document.querySelector('#queue-position').textContent.includes('第 3 位'));checks.push('cancel_and_retry_refresh_task_position_and_timing');
  await api('/fixture/control/start',{});await until(async()=>await api('/fixture').then(x=>x.state.waiting));
  const detail=await ctx.newPage();await detail.goto(base+'/tasks/'+f.daily);await detail.waitForFunction(()=>document.querySelector('#queue-position').textContent.includes('第 1 位'));assert.match(await detail.locator('#queue-position').textContent(),/另有 1 项/);checks.push('detail_excludes_executing_task_from_waiting_rank');
  await page.goto(base+'/tasks?status=active');await ready();assert.match(await page.locator('#executing-list').textContent(),/演示采集策略/);assert.match(await page.locator('#worker-state').textContent(),/运行中/);await shot('queue-live');
  await page.locator('#auto-refresh').uncheck();await api('/fixture/control/release',{});await until(async()=>await api('/api/tasks/'+f.daily).then(x=>x.status==='succeeded'));assert.equal(await page.locator('#count-queued').textContent(),'2');checks.push('auto_refresh_can_be_paused');
  await page.locator('#auto-refresh').check();await page.waitForFunction(()=>document.querySelector('#count-active').textContent==='0');await detail.waitForFunction(()=>document.querySelector('#queue-position').textContent==='本任务已结束。');checks.push('completion_updates_overview_and_final_task_snapshot');await detail.close();
  await page.locator('#clear-filters').click();await ready();await page.locator('[name=query]').fill('离线示例：每日脚本排队');await page.getByRole('button',{name:'筛选任务',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#queue-total').textContent.includes('1 项'));await rows.first().getByRole('link',{name:'打开草稿',exact:true}).click();await page.waitForURL('**/scripts/pkg_*');checks.push('completed_daily_task_opens_original_draft');
  await page.goto(base+'/tasks');await ready();await page.route('**/api/task-queue?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'离线验证临时故障'})}));await page.locator('#refresh').click();await page.waitForFunction(()=>document.querySelector('#queue-notice').textContent.includes('上次成功取得'));assert.ok(await rows.count()>1);await page.unroute('**/api/task-queue?*');await page.locator('#refresh').click();await ready();checks.push('refresh_failure_keeps_previous_records_with_stale_notice');
  await page.setViewportSize({width:390,height:844});await page.goto(base+'/tasks?status=failed');await ready();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot('queue-mobile');await page.goto(base+'/tasks/'+f.daily);await page.locator('#queue-duration').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);checks.push('task_center_and_detail_fit_mobile');
  assert.deepEqual(errors,[]);checks.push('no_javascript_errors');const report={passed:checks.length,checks,browser:browser.version(),errors};await fs.writeFile(path.join(out,'task-monitor-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
