// Optional browser QA: start smoke_news_data.py --serve PORT first.
const { chromium } = require('playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
  const base = process.argv[2] || 'http://127.0.0.1:18190';
  const out = process.argv[3] || 'browser-results';
  await fs.mkdir(out, {recursive:true});
  const browser = await chromium.launch({headless:true, executablePath: process.env.BROWSER_BIN || undefined, args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1440,height:1050}});
  const errors = [];
  page.on('pageerror', e => errors.push(String(e)));
  const checks = [];
  try {
    await page.goto(base + '/articles');
    await page.locator('[name=q]').fill('芯片');
    await page.locator('[name=limit]').fill('2');
    await page.getByRole('button',{name:'搜索',exact:true}).click();
    assert.equal(await page.locator('table tr').count(),3);
    checks.push('search_form');
    await page.getByRole('link',{name:'下一页',exact:true}).click();
    assert.equal(await page.locator('table tr').count(),2);
    assert.match(page.url(), /offset=2/);
    checks.push('pagination_preserves_query');
    await page.locator('table td a').first().click();
    await page.getByRole('heading',{name:'与上一个版本的正文差异'}).waitFor();
    assert.match(await page.locator('main').innerText(), /最新 r2/);
    checks.push('version_and_diff');
    await page.screenshot({path:path.join(out,'article-version.png'),fullPage:true});
    await page.getByRole('link',{name:'r1',exact:true}).click();
    assert.match(await page.locator('main').innerText(), /当前查看 r1/);
    assert.equal(await page.getByRole('heading',{name:'与上一个版本的正文差异'}).count(),0);
    checks.push('historical_version_navigation');
    await page.goto(base + '/articles?limit=2');
    await page.locator('[name=q]').fill('华星 交付');
    await page.locator('[name=mode]').selectOption('terms');
    await page.locator('[name=duplicates]').selectOption('no');
    await page.getByRole('button',{name:'搜索',exact:true}).click();
    assert.match(await page.locator('h1').innerText(), /共 2 条/);
    assert.equal(await page.getByRole('link',{name:'下一页',exact:true}).count(),0);
    checks.push('multi_term_and_independent_filter');
    await page.screenshot({path:path.join(out,'article-search.png'),fullPage:true});
    await page.goto(base + '/events');
    await page.locator('[name=q]').fill('采购方');
    await page.getByRole('button',{name:'搜索',exact:true}).click();
    await page.locator('table td a').first().click();
    assert.match(await page.locator('main').innerText(), /独立报道: 2/);
    assert.match(await page.locator('main').innerText(), /转载\/副本: 1/);
    checks.push('event_fulltext_and_source_counts');
    await page.screenshot({path:path.join(out,'event-evidence.png'),fullPage:true});
    assert.deepEqual(errors, []);
    checks.push('no_javascript_errors');
    const report = {passed:checks.length,checks,browser:browser.version(),errors};
    await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2)+'\n');
    console.log(JSON.stringify(report));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode=1; });
